// Package entity defines the core domain entities and validation logic for the application.
package entity

import (
	"errors"
	"time"
)

// Sentinel errors for ArticleEmbedding validation.
var (
	// ErrInvalidEmbeddingType indicates that the embedding type is not valid
	ErrInvalidEmbeddingType = errors.New("invalid embedding type")

	// ErrInvalidEmbeddingProvider indicates that the embedding provider is not valid
	ErrInvalidEmbeddingProvider = errors.New("invalid embedding provider")

	// ErrInvalidEmbeddingDimension indicates that the embedding dimension does not match the vector length
	ErrInvalidEmbeddingDimension = errors.New("invalid embedding dimension")

	// ErrEmptyEmbedding indicates that the embedding vector is empty
	ErrEmptyEmbedding = errors.New("empty embedding vector")
)

// EmbeddingType represents the type of content that was embedded.
type EmbeddingType string

const (
	// EmbeddingTypeTitle represents an embedding of the article title
	EmbeddingTypeTitle EmbeddingType = "title"

	// EmbeddingTypeContent represents an embedding of the full article content
	EmbeddingTypeContent EmbeddingType = "content"

	// EmbeddingTypeSummary represents an embedding of the article summary
	EmbeddingTypeSummary EmbeddingType = "summary"
)

// IsValid checks if the EmbeddingType is a valid value.
func (t EmbeddingType) IsValid() bool {
	switch t {
	case EmbeddingTypeTitle, EmbeddingTypeContent, EmbeddingTypeSummary:
		return true
	default:
		return false
	}
}

// EmbeddingProvider represents the service that generated the embedding.
type EmbeddingProvider string

const (
	// EmbeddingProviderOpenAI represents embeddings generated by OpenAI
	EmbeddingProviderOpenAI EmbeddingProvider = "openai"

	// EmbeddingProviderVoyage represents embeddings generated by Voyage AI
	EmbeddingProviderVoyage EmbeddingProvider = "voyage"
)

// IsValid checks if the EmbeddingProvider is a valid value.
func (p EmbeddingProvider) IsValid() bool {
	switch p {
	case EmbeddingProviderOpenAI, EmbeddingProviderVoyage:
		return true
	default:
		return false
	}
}

// ArticleEmbedding represents a vector embedding of an article.
// It stores the embedding vector along with metadata about the embedding type,
// provider, model, and dimension for semantic search capabilities.
type ArticleEmbedding struct {
	ID            int64
	ArticleID     int64
	EmbeddingType EmbeddingType
	Provider      EmbeddingProvider
	Model         string
	Dimension     int32
	Embedding     []float32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Validate checks if the ArticleEmbedding entity has valid field values.
// Returns an error if any validation rule fails.
func (e *ArticleEmbedding) Validate() error {
	// Validate ArticleID is positive
	if e.ArticleID <= 0 {
		return &ValidationError{
			Field:   "ArticleID",
			Message: "must be positive",
		}
	}

	// Validate EmbeddingType
	if !e.EmbeddingType.IsValid() {
		return ErrInvalidEmbeddingType
	}

	// Validate Provider
	if !e.Provider.IsValid() {
		return ErrInvalidEmbeddingProvider
	}

	// Validate Embedding is not empty
	if len(e.Embedding) == 0 {
		return ErrEmptyEmbedding
	}

	// Validate Dimension matches embedding length
	// #nosec G115 -- embedding dimension is always within int32 range (max 1536)
	if int32(len(e.Embedding)) != e.Dimension {
		return ErrInvalidEmbeddingDimension
	}

	return nil
}
