version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  default: none
  enable:
    - ineffassign
    - errcheck
    - govet
    - staticcheck
    - unused
  exclusions:
    paths:
      - docs
      - vendor
      - node_modules
      - "scripts/.*\\.go"
    rules:
      - path: "scripts/.*\\.go"
        linters:
          - errcheck
