// Copyright 2026 catchup-feed. All rights reserved.
// AI service protocol buffer definitions for gRPC communication.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: article.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleAI_EmbedArticle_FullMethodName          = "/catchup.ai.v1.ArticleAI/EmbedArticle"
	ArticleAI_SearchSimilar_FullMethodName         = "/catchup.ai.v1.ArticleAI/SearchSimilar"
	ArticleAI_QueryArticles_FullMethodName         = "/catchup.ai.v1.ArticleAI/QueryArticles"
	ArticleAI_GenerateWeeklySummary_FullMethodName = "/catchup.ai.v1.ArticleAI/GenerateWeeklySummary"
)

// ArticleAIClient is the client API for ArticleAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArticleAI provides AI-powered operations on articles.
type ArticleAIClient interface {
	// EmbedArticle generates an embedding vector for an article.
	// The embedding is stored by catchup-ai in the vector database.
	EmbedArticle(ctx context.Context, in *EmbedArticleRequest, opts ...grpc.CallOption) (*EmbedArticleResponse, error)
	// SearchSimilar finds articles semantically similar to a query.
	SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error)
	// QueryArticles performs RAG-based question answering over articles.
	QueryArticles(ctx context.Context, in *QueryArticlesRequest, opts ...grpc.CallOption) (*QueryArticlesResponse, error)
	// GenerateWeeklySummary generates a summary of recent articles.
	GenerateWeeklySummary(ctx context.Context, in *GenerateWeeklySummaryRequest, opts ...grpc.CallOption) (*GenerateWeeklySummaryResponse, error)
}

type articleAIClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleAIClient(cc grpc.ClientConnInterface) ArticleAIClient {
	return &articleAIClient{cc}
}

func (c *articleAIClient) EmbedArticle(ctx context.Context, in *EmbedArticleRequest, opts ...grpc.CallOption) (*EmbedArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedArticleResponse)
	err := c.cc.Invoke(ctx, ArticleAI_EmbedArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleAIClient) SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSimilarResponse)
	err := c.cc.Invoke(ctx, ArticleAI_SearchSimilar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleAIClient) QueryArticles(ctx context.Context, in *QueryArticlesRequest, opts ...grpc.CallOption) (*QueryArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryArticlesResponse)
	err := c.cc.Invoke(ctx, ArticleAI_QueryArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleAIClient) GenerateWeeklySummary(ctx context.Context, in *GenerateWeeklySummaryRequest, opts ...grpc.CallOption) (*GenerateWeeklySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWeeklySummaryResponse)
	err := c.cc.Invoke(ctx, ArticleAI_GenerateWeeklySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleAIServer is the server API for ArticleAI service.
// All implementations must embed UnimplementedArticleAIServer
// for forward compatibility.
//
// ArticleAI provides AI-powered operations on articles.
type ArticleAIServer interface {
	// EmbedArticle generates an embedding vector for an article.
	// The embedding is stored by catchup-ai in the vector database.
	EmbedArticle(context.Context, *EmbedArticleRequest) (*EmbedArticleResponse, error)
	// SearchSimilar finds articles semantically similar to a query.
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
	// QueryArticles performs RAG-based question answering over articles.
	QueryArticles(context.Context, *QueryArticlesRequest) (*QueryArticlesResponse, error)
	// GenerateWeeklySummary generates a summary of recent articles.
	GenerateWeeklySummary(context.Context, *GenerateWeeklySummaryRequest) (*GenerateWeeklySummaryResponse, error)
	mustEmbedUnimplementedArticleAIServer()
}

// UnimplementedArticleAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleAIServer struct{}

func (UnimplementedArticleAIServer) EmbedArticle(context.Context, *EmbedArticleRequest) (*EmbedArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedArticle not implemented")
}
func (UnimplementedArticleAIServer) SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSimilar not implemented")
}
func (UnimplementedArticleAIServer) QueryArticles(context.Context, *QueryArticlesRequest) (*QueryArticlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryArticles not implemented")
}
func (UnimplementedArticleAIServer) GenerateWeeklySummary(context.Context, *GenerateWeeklySummaryRequest) (*GenerateWeeklySummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateWeeklySummary not implemented")
}
func (UnimplementedArticleAIServer) mustEmbedUnimplementedArticleAIServer() {}
func (UnimplementedArticleAIServer) testEmbeddedByValue()                   {}

// UnsafeArticleAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleAIServer will
// result in compilation errors.
type UnsafeArticleAIServer interface {
	mustEmbedUnimplementedArticleAIServer()
}

func RegisterArticleAIServer(s grpc.ServiceRegistrar, srv ArticleAIServer) {
	// If the following call panics, it indicates UnimplementedArticleAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleAI_ServiceDesc, srv)
}

func _ArticleAI_EmbedArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAIServer).EmbedArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAI_EmbedArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAIServer).EmbedArticle(ctx, req.(*EmbedArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleAI_SearchSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAIServer).SearchSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAI_SearchSimilar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAIServer).SearchSimilar(ctx, req.(*SearchSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleAI_QueryArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAIServer).QueryArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAI_QueryArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAIServer).QueryArticles(ctx, req.(*QueryArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleAI_GenerateWeeklySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWeeklySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleAIServer).GenerateWeeklySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleAI_GenerateWeeklySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleAIServer).GenerateWeeklySummary(ctx, req.(*GenerateWeeklySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleAI_ServiceDesc is the grpc.ServiceDesc for ArticleAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catchup.ai.v1.ArticleAI",
	HandlerType: (*ArticleAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmbedArticle",
			Handler:    _ArticleAI_EmbedArticle_Handler,
		},
		{
			MethodName: "SearchSimilar",
			Handler:    _ArticleAI_SearchSimilar_Handler,
		},
		{
			MethodName: "QueryArticles",
			Handler:    _ArticleAI_QueryArticles_Handler,
		},
		{
			MethodName: "GenerateWeeklySummary",
			Handler:    _ArticleAI_GenerateWeeklySummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
