// Copyright 2026 catchup-feed. All rights reserved.
// AI service protocol buffer definitions for gRPC communication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: article.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SummaryPeriod defines the time range for summarization.
type SummaryPeriod int32

const (
	SummaryPeriod_SUMMARY_PERIOD_UNSPECIFIED SummaryPeriod = 0
	SummaryPeriod_SUMMARY_PERIOD_WEEK        SummaryPeriod = 1
	SummaryPeriod_SUMMARY_PERIOD_MONTH       SummaryPeriod = 2
)

// Enum value maps for SummaryPeriod.
var (
	SummaryPeriod_name = map[int32]string{
		0: "SUMMARY_PERIOD_UNSPECIFIED",
		1: "SUMMARY_PERIOD_WEEK",
		2: "SUMMARY_PERIOD_MONTH",
	}
	SummaryPeriod_value = map[string]int32{
		"SUMMARY_PERIOD_UNSPECIFIED": 0,
		"SUMMARY_PERIOD_WEEK":        1,
		"SUMMARY_PERIOD_MONTH":       2,
	}
)

func (x SummaryPeriod) Enum() *SummaryPeriod {
	p := new(SummaryPeriod)
	*p = x
	return p
}

func (x SummaryPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SummaryPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_article_proto_enumTypes[0].Descriptor()
}

func (SummaryPeriod) Type() protoreflect.EnumType {
	return &file_article_proto_enumTypes[0]
}

func (x SummaryPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SummaryPeriod.Descriptor instead.
func (SummaryPeriod) EnumDescriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

// EmbedArticleRequest contains article content for embedding generation.
type EmbedArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Unique article identifier.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Required: Article title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Required: Article content or summary for embedding.
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Optional: Article URL for reference.
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedArticleRequest) Reset() {
	*x = EmbedArticleRequest{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedArticleRequest) ProtoMessage() {}

func (x *EmbedArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedArticleRequest.ProtoReflect.Descriptor instead.
func (*EmbedArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedArticleRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *EmbedArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmbedArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbedArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// EmbedArticleResponse contains the result of embedding generation.
type EmbedArticleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if embedding was generated and stored successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success is false.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Dimension of the generated embedding (e.g., 1536 for OpenAI).
	Dimension     int32 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedArticleResponse) Reset() {
	*x = EmbedArticleResponse{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedArticleResponse) ProtoMessage() {}

func (x *EmbedArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedArticleResponse.ProtoReflect.Descriptor instead.
func (*EmbedArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbedArticleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EmbedArticleResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

// SearchSimilarRequest contains the query for semantic search.
type SearchSimilarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Natural language query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional: Maximum number of results. Default: 10, Max: 50.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional: Minimum similarity threshold (0.0 to 1.0). Default: 0.5.
	MinSimilarity float32 `protobuf:"fixed32,3,opt,name=min_similarity,json=minSimilarity,proto3" json:"min_similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *SearchSimilarRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSimilarRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSimilarRequest) GetMinSimilarity() float32 {
	if x != nil {
		return x.MinSimilarity
	}
	return 0
}

// SearchSimilarResponse contains search results.
type SearchSimilarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of similar articles sorted by similarity (highest first).
	Articles []*SimilarArticle `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Total number of articles searched.
	TotalSearched int64 `protobuf:"varint,2,opt,name=total_searched,json=totalSearched,proto3" json:"total_searched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *SearchSimilarResponse) GetArticles() []*SimilarArticle {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *SearchSimilarResponse) GetTotalSearched() int64 {
	if x != nil {
		return x.TotalSearched
	}
	return 0
}

// SimilarArticle represents an article with similarity score.
type SimilarArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article ID for fetching full article from repository.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Article title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Article URL.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Cosine similarity score (0.0 to 1.0).
	Similarity float32 `protobuf:"fixed32,4,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Brief excerpt highlighting relevance.
	Excerpt       string `protobuf:"bytes,5,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarArticle) Reset() {
	*x = SimilarArticle{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarArticle) ProtoMessage() {}

func (x *SimilarArticle) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarArticle.ProtoReflect.Descriptor instead.
func (*SimilarArticle) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *SimilarArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *SimilarArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimilarArticle) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SimilarArticle) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *SimilarArticle) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

// QueryArticlesRequest contains the question for RAG-based Q&A.
type QueryArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Natural language question.
	Question string `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	// Optional: Maximum articles to use as context. Default: 5, Max: 20.
	MaxContext    int32 `protobuf:"varint,2,opt,name=max_context,json=maxContext,proto3" json:"max_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryArticlesRequest) Reset() {
	*x = QueryArticlesRequest{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticlesRequest) ProtoMessage() {}

func (x *QueryArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticlesRequest.ProtoReflect.Descriptor instead.
func (*QueryArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *QueryArticlesRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QueryArticlesRequest) GetMaxContext() int32 {
	if x != nil {
		return x.MaxContext
	}
	return 0
}

// QueryArticlesResponse contains the AI-generated answer.
type QueryArticlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AI-generated answer to the question.
	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// Source articles used to generate the answer.
	Sources []*SourceArticle `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Confidence score (0.0 to 1.0).
	Confidence    float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryArticlesResponse) Reset() {
	*x = QueryArticlesResponse{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArticlesResponse) ProtoMessage() {}

func (x *QueryArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArticlesResponse.ProtoReflect.Descriptor instead.
func (*QueryArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *QueryArticlesResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryArticlesResponse) GetSources() []*SourceArticle {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QueryArticlesResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// SourceArticle represents an article cited in the answer.
type SourceArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article ID.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Article title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Article URL.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Relevance to the answer (0.0 to 1.0).
	Relevance     float32 `protobuf:"fixed32,4,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceArticle) Reset() {
	*x = SourceArticle{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceArticle) ProtoMessage() {}

func (x *SourceArticle) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceArticle.ProtoReflect.Descriptor instead.
func (*SourceArticle) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *SourceArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *SourceArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SourceArticle) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SourceArticle) GetRelevance() float32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

// GenerateWeeklySummaryRequest contains parameters for summary generation.
type GenerateWeeklySummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Summary period type.
	Period SummaryPeriod `protobuf:"varint,1,opt,name=period,proto3,enum=catchup.ai.v1.SummaryPeriod" json:"period,omitempty"`
	// Optional: Maximum highlights to include. Default: 5, Max: 10.
	MaxHighlights int32 `protobuf:"varint,2,opt,name=max_highlights,json=maxHighlights,proto3" json:"max_highlights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWeeklySummaryRequest) Reset() {
	*x = GenerateWeeklySummaryRequest{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWeeklySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWeeklySummaryRequest) ProtoMessage() {}

func (x *GenerateWeeklySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWeeklySummaryRequest.ProtoReflect.Descriptor instead.
func (*GenerateWeeklySummaryRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateWeeklySummaryRequest) GetPeriod() SummaryPeriod {
	if x != nil {
		return x.Period
	}
	return SummaryPeriod_SUMMARY_PERIOD_UNSPECIFIED
}

func (x *GenerateWeeklySummaryRequest) GetMaxHighlights() int32 {
	if x != nil {
		return x.MaxHighlights
	}
	return 0
}

// GenerateWeeklySummaryResponse contains the generated summary.
type GenerateWeeklySummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall summary of articles in the period.
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// Key highlights/topics from the period.
	Highlights []*Highlight `protobuf:"bytes,2,rep,name=highlights,proto3" json:"highlights,omitempty"`
	// Number of articles summarized.
	ArticleCount int32 `protobuf:"varint,3,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	// Date range covered (ISO 8601).
	StartDate     string `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWeeklySummaryResponse) Reset() {
	*x = GenerateWeeklySummaryResponse{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWeeklySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWeeklySummaryResponse) ProtoMessage() {}

func (x *GenerateWeeklySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWeeklySummaryResponse.ProtoReflect.Descriptor instead.
func (*GenerateWeeklySummaryResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateWeeklySummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GenerateWeeklySummaryResponse) GetHighlights() []*Highlight {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *GenerateWeeklySummaryResponse) GetArticleCount() int32 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *GenerateWeeklySummaryResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GenerateWeeklySummaryResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Highlight represents a key topic or trend.
type Highlight struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic name or title.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Brief description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Number of related articles.
	ArticleCount  int32 `protobuf:"varint,3,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Highlight) Reset() {
	*x = Highlight{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Highlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Highlight) ProtoMessage() {}

func (x *Highlight) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Highlight.ProtoReflect.Descriptor instead.
func (*Highlight) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *Highlight) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Highlight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Highlight) GetArticleCount() int32 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\rcatchup.ai.v1\"v\n" +
	"\x13EmbedArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"s\n" +
	"\x14EmbedArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\x05R\tdimension\"i\n" +
	"\x14SearchSimilarRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12%\n" +
	"\x0emin_similarity\x18\x03 \x01(\x02R\rminSimilarity\"y\n" +
	"\x15SearchSimilarResponse\x129\n" +
	"\barticles\x18\x01 \x03(\v2\x1d.catchup.ai.v1.SimilarArticleR\barticles\x12%\n" +
	"\x0etotal_searched\x18\x02 \x01(\x03R\rtotalSearched\"\x91\x01\n" +
	"\x0eSimilarArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x02R\n" +
	"similarity\x12\x18\n" +
	"\aexcerpt\x18\x05 \x01(\tR\aexcerpt\"S\n" +
	"\x14QueryArticlesRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1f\n" +
	"\vmax_context\x18\x02 \x01(\x05R\n" +
	"maxContext\"\x87\x01\n" +
	"\x15QueryArticlesResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x126\n" +
	"\asources\x18\x02 \x03(\v2\x1c.catchup.ai.v1.SourceArticleR\asources\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"t\n" +
	"\rSourceArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1c\n" +
	"\trelevance\x18\x04 \x01(\x02R\trelevance\"{\n" +
	"\x1cGenerateWeeklySummaryRequest\x124\n" +
	"\x06period\x18\x01 \x01(\x0e2\x1c.catchup.ai.v1.SummaryPeriodR\x06period\x12%\n" +
	"\x0emax_highlights\x18\x02 \x01(\x05R\rmaxHighlights\"\xd2\x01\n" +
	"\x1dGenerateWeeklySummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x128\n" +
	"\n" +
	"highlights\x18\x02 \x03(\v2\x18.catchup.ai.v1.HighlightR\n" +
	"highlights\x12#\n" +
	"\rarticle_count\x18\x03 \x01(\x05R\farticleCount\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"h\n" +
	"\tHighlight\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rarticle_count\x18\x03 \x01(\x05R\farticleCount*b\n" +
	"\rSummaryPeriod\x12\x1e\n" +
	"\x1aSUMMARY_PERIOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SUMMARY_PERIOD_WEEK\x10\x01\x12\x18\n" +
	"\x14SUMMARY_PERIOD_MONTH\x10\x022\x90\x03\n" +
	"\tArticleAI\x12W\n" +
	"\fEmbedArticle\x12\".catchup.ai.v1.EmbedArticleRequest\x1a#.catchup.ai.v1.EmbedArticleResponse\x12Z\n" +
	"\rSearchSimilar\x12#.catchup.ai.v1.SearchSimilarRequest\x1a$.catchup.ai.v1.SearchSimilarResponse\x12Z\n" +
	"\rQueryArticles\x12#.catchup.ai.v1.QueryArticlesRequest\x1a$.catchup.ai.v1.QueryArticlesResponse\x12r\n" +
	"\x15GenerateWeeklySummary\x12+.catchup.ai.v1.GenerateWeeklySummaryRequest\x1a,.catchup.ai.v1.GenerateWeeklySummaryResponseB,Z*catchup-feed/internal/interface/grpc/pb/aib\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_article_proto_goTypes = []any{
	(SummaryPeriod)(0),                    // 0: catchup.ai.v1.SummaryPeriod
	(*EmbedArticleRequest)(nil),           // 1: catchup.ai.v1.EmbedArticleRequest
	(*EmbedArticleResponse)(nil),          // 2: catchup.ai.v1.EmbedArticleResponse
	(*SearchSimilarRequest)(nil),          // 3: catchup.ai.v1.SearchSimilarRequest
	(*SearchSimilarResponse)(nil),         // 4: catchup.ai.v1.SearchSimilarResponse
	(*SimilarArticle)(nil),                // 5: catchup.ai.v1.SimilarArticle
	(*QueryArticlesRequest)(nil),          // 6: catchup.ai.v1.QueryArticlesRequest
	(*QueryArticlesResponse)(nil),         // 7: catchup.ai.v1.QueryArticlesResponse
	(*SourceArticle)(nil),                 // 8: catchup.ai.v1.SourceArticle
	(*GenerateWeeklySummaryRequest)(nil),  // 9: catchup.ai.v1.GenerateWeeklySummaryRequest
	(*GenerateWeeklySummaryResponse)(nil), // 10: catchup.ai.v1.GenerateWeeklySummaryResponse
	(*Highlight)(nil),                     // 11: catchup.ai.v1.Highlight
}
var file_article_proto_depIdxs = []int32{
	5,  // 0: catchup.ai.v1.SearchSimilarResponse.articles:type_name -> catchup.ai.v1.SimilarArticle
	8,  // 1: catchup.ai.v1.QueryArticlesResponse.sources:type_name -> catchup.ai.v1.SourceArticle
	0,  // 2: catchup.ai.v1.GenerateWeeklySummaryRequest.period:type_name -> catchup.ai.v1.SummaryPeriod
	11, // 3: catchup.ai.v1.GenerateWeeklySummaryResponse.highlights:type_name -> catchup.ai.v1.Highlight
	1,  // 4: catchup.ai.v1.ArticleAI.EmbedArticle:input_type -> catchup.ai.v1.EmbedArticleRequest
	3,  // 5: catchup.ai.v1.ArticleAI.SearchSimilar:input_type -> catchup.ai.v1.SearchSimilarRequest
	6,  // 6: catchup.ai.v1.ArticleAI.QueryArticles:input_type -> catchup.ai.v1.QueryArticlesRequest
	9,  // 7: catchup.ai.v1.ArticleAI.GenerateWeeklySummary:input_type -> catchup.ai.v1.GenerateWeeklySummaryRequest
	2,  // 8: catchup.ai.v1.ArticleAI.EmbedArticle:output_type -> catchup.ai.v1.EmbedArticleResponse
	4,  // 9: catchup.ai.v1.ArticleAI.SearchSimilar:output_type -> catchup.ai.v1.SearchSimilarResponse
	7,  // 10: catchup.ai.v1.ArticleAI.QueryArticles:output_type -> catchup.ai.v1.QueryArticlesResponse
	10, // 11: catchup.ai.v1.ArticleAI.GenerateWeeklySummary:output_type -> catchup.ai.v1.GenerateWeeklySummaryResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		EnumInfos:         file_article_proto_enumTypes,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
