package postgres_test

import (
	"context"
	"regexp"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"catchup-feed/internal/infra/adapter/persistence/postgres"
	"catchup-feed/internal/learning"
	"catchup-feed/internal/repository"
)

func newLearningRepo(t *testing.T) (repository.LearningRepository, sqlmock.Sqlmock, func()) {
	t.Helper()
	db, mock, err := sqlmock.New()
	require.NoError(t, err)
	return postgres.NewLearningRepo(db), mock, func() { _ = db.Close() }
}

func testDay(y int, m time.Month, d int) time.Time {
	return time.Date(y, m, d, 0, 0, 0, 0, time.UTC)
}

var learningItemCols = []string{
	"id", "kind", "article_id", "book_id", "concept", "question", "answer",
	"provider", "stage", "due_on", "retired_at", "created_at",
}

func TestLearningRepo_InsertItem(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	articleID := int64(42)
	item := learning.NewItem{
		Kind:      learning.KindArticle,
		ArticleID: &articleID,
		Concept:   "goroutine leak",
		Question:  "Q",
		Answer:    "A",
		Provider:  "gemini",
	}
	// stage は 0 固定、due_on はテキスト + ::date で渡す(§12-10)。
	mock.ExpectQuery(regexp.QuoteMeta("INSERT INTO learning_items")).
		WithArgs(learning.KindArticle, &articleID, nil, "goroutine leak", "Q", "A", "gemini", "2026-07-08").
		WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(int64(5)))

	id, err := repo.InsertItem(context.Background(), item, testDay(2026, 7, 8))
	require.NoError(t, err)
	assert.Equal(t, int64(5), id)
	assert.NoError(t, mock.ExpectationsWereMet())
}

// TestLearningRepo_InsertItem_BookProviderEnforced pins §12-4: the
// application layer rejects a kind='book' item generated by a cloud
// provider before any SQL is issued (C-12 — 書籍はローカル LLM 限定).
func TestLearningRepo_InsertItem_BookProviderEnforced(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	bookID := int64(7)
	item := learning.NewItem{
		Kind:    learning.KindBook,
		BookID:  &bookID,
		Concept: "c", Question: "q", Answer: "a",
		Provider: "gemini",
	}
	_, err := repo.InsertItem(context.Background(), item, testDay(2026, 7, 8))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "ollama")
	assert.NoError(t, mock.ExpectationsWereMet(), "no SQL may be issued for an invalid item")
}

func TestLearningRepo_ListDue(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	articleID := int64(42)
	created := time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC)
	mock.ExpectQuery(regexp.QuoteMeta("WHERE retired_at IS NULL AND due_on <= $1::date")).
		WithArgs("2026-07-07", 4).
		WillReturnRows(sqlmock.NewRows(learningItemCols).
			AddRow(int64(1), "article", &articleID, nil, "c1", "q1", "a1", "gemini", 0, testDay(2026, 7, 6), nil, created).
			AddRow(int64(2), "book", nil, int64(7), "c2", "q2", "a2", "ollama", 1, testDay(2026, 7, 7), nil, created))

	items, err := repo.ListDue(context.Background(), testDay(2026, 7, 7), 4)
	require.NoError(t, err)
	require.Len(t, items, 2)
	assert.Equal(t, int64(1), items[0].ID)
	assert.Equal(t, learning.KindArticle, items[0].Kind)
	assert.Equal(t, articleID, *items[0].ArticleID)
	assert.Equal(t, learning.KindBook, items[1].Kind)
	assert.Equal(t, 1, items[1].Stage)
	assert.True(t, items[1].DueOn.Equal(testDay(2026, 7, 7)))
	assert.NoError(t, mock.ExpectationsWereMet())
}

func TestLearningRepo_RecordAsked(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	mock.ExpectBegin()
	// 2件目は同日再実行相当で conflict(0 rows)でもエラーにならない。
	mock.ExpectExec(regexp.QuoteMeta("INSERT INTO review_logs")).
		WithArgs(int64(1), int64(99), "2026-07-07").
		WillReturnResult(sqlmock.NewResult(0, 1))
	mock.ExpectExec(regexp.QuoteMeta("INSERT INTO review_logs")).
		WithArgs(int64(2), int64(99), "2026-07-07").
		WillReturnResult(sqlmock.NewResult(0, 0))
	mock.ExpectCommit()

	err := repo.RecordAsked(context.Background(), []int64{1, 2}, 99, testDay(2026, 7, 7))
	require.NoError(t, err)
	assert.NoError(t, mock.ExpectationsWereMet())
}

func TestLearningRepo_RecordAsked_Empty(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	// 出題ゼロの日は SQL を発行しない。
	require.NoError(t, repo.RecordAsked(context.Background(), nil, 99, testDay(2026, 7, 7)))
	assert.NoError(t, mock.ExpectationsWereMet())
}

// TestLearningRepo_AutoResolve covers the shape of the D-17 auto-advance:
// the atomic claim UPDATE (not-yet-set checks in the WHERE, §12-9), the
// per-item dedupe (item 5 has two stale logs but advances once), the
// ascending lock order, and graduation for an item on the final rung.
func TestLearningRepo_AutoResolve(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	ladder := []int{1, 7, 30}
	resolveDay := testDay(2026, 7, 7)

	mock.ExpectBegin()
	// Claim returns logs for items 7, 5, 5 — dedupe to {5, 7}, locked in
	// ascending order.
	mock.ExpectQuery(regexp.QuoteMeta("WHERE result IS NULL AND graded_at IS NULL AND asked_on <= $2::date")).
		WithArgs(learning.ResultAuto, "2026-07-05").
		WillReturnRows(sqlmock.NewRows([]string{"item_id"}).
			AddRow(int64(7)).AddRow(int64(5)).AddRow(int64(5)))

	// item 5: stage 0 -> 1, due = resolveDay + 7d.
	mock.ExpectQuery(regexp.QuoteMeta("FOR UPDATE")).
		WithArgs(int64(5)).
		WillReturnRows(sqlmock.NewRows([]string{"stage"}).AddRow(0))
	mock.ExpectExec(regexp.QuoteMeta("UPDATE learning_items")).
		WithArgs(int64(5), 1, "2026-07-14", false).
		WillReturnResult(sqlmock.NewResult(0, 1))

	// item 7: stage 2 (最終段) -> 卒業。
	mock.ExpectQuery(regexp.QuoteMeta("FOR UPDATE")).
		WithArgs(int64(7)).
		WillReturnRows(sqlmock.NewRows([]string{"stage"}).AddRow(2))
	mock.ExpectExec(regexp.QuoteMeta("UPDATE learning_items")).
		WithArgs(int64(7), 3, "2026-07-07", true).
		WillReturnResult(sqlmock.NewResult(0, 1))
	mock.ExpectCommit()

	resolved, err := repo.AutoResolve(context.Background(), testDay(2026, 7, 5), resolveDay, ladder)
	require.NoError(t, err)
	assert.Equal(t, 3, resolved, "all three logs are closed even though items advance once each")
	assert.NoError(t, mock.ExpectationsWereMet())
}

// TestLearningRepo_AutoResolve_RetiredItemSkipped: a stale log of an item
// retired in the meantime is closed, but the item state stays terminal.
func TestLearningRepo_AutoResolve_RetiredItemSkipped(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	mock.ExpectBegin()
	mock.ExpectQuery(regexp.QuoteMeta("RETURNING item_id")).
		WithArgs(learning.ResultAuto, "2026-07-05").
		WillReturnRows(sqlmock.NewRows([]string{"item_id"}).AddRow(int64(9)))
	// retired_at IS NULL で絞るため行が返らない → 遷移スキップ。
	mock.ExpectQuery(regexp.QuoteMeta("FOR UPDATE")).
		WithArgs(int64(9)).
		WillReturnRows(sqlmock.NewRows([]string{"stage"}))
	mock.ExpectCommit()

	resolved, err := repo.AutoResolve(context.Background(), testDay(2026, 7, 5), testDay(2026, 7, 7), []int{1, 7, 30})
	require.NoError(t, err)
	assert.Equal(t, 1, resolved)
	assert.NoError(t, mock.ExpectationsWereMet())
}

func TestLearningRepo_CountOverdueActive(t *testing.T) {
	repo, mock, closeFn := newLearningRepo(t)
	defer closeFn()

	// 期日超過は due_on < 放送日(当日 due は超過ではない、§5.2)。
	mock.ExpectQuery(regexp.QuoteMeta("WHERE retired_at IS NULL AND due_on < $1::date")).
		WithArgs("2026-07-07").
		WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(31))

	n, err := repo.CountOverdueActive(context.Background(), testDay(2026, 7, 7))
	require.NoError(t, err)
	assert.Equal(t, 31, n)
	assert.NoError(t, mock.ExpectationsWereMet())
}
