// Copyright 2026 catchup-feed. All rights reserved.
// Embedding service protocol buffer definitions for gRPC communication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: embedding.proto

package embedding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreEmbeddingRequest contains the embedding data to store.
type StoreEmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: ID of the article this embedding belongs to.
	// Must be a positive integer referencing an existing article.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Required: Type of content that was embedded.
	// Valid values: "title", "content", "summary"
	EmbeddingType string `protobuf:"bytes,2,opt,name=embedding_type,json=embeddingType,proto3" json:"embedding_type,omitempty"`
	// Required: AI provider that generated the embedding.
	// Valid values: "openai", "voyage"
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Required: Model name that generated the embedding.
	// Example: "text-embedding-3-small", "voyage-3"
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// Required: Dimension of the embedding vector.
	// Must match the length of embedding field.
	Dimension int32 `protobuf:"varint,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	// Required: The embedding vector.
	// Length must match dimension field.
	Embedding     []float32 `protobuf:"fixed32,6,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEmbeddingRequest) Reset() {
	*x = StoreEmbeddingRequest{}
	mi := &file_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEmbeddingRequest) ProtoMessage() {}

func (x *StoreEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*StoreEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *StoreEmbeddingRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *StoreEmbeddingRequest) GetEmbeddingType() string {
	if x != nil {
		return x.EmbeddingType
	}
	return ""
}

func (x *StoreEmbeddingRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StoreEmbeddingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StoreEmbeddingRequest) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *StoreEmbeddingRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// StoreEmbeddingResponse contains the result of the store operation.
type StoreEmbeddingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the operation succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// ID of the stored/updated embedding.
	// Only populated if success is true.
	EmbeddingId int64 `protobuf:"varint,2,opt,name=embedding_id,json=embeddingId,proto3" json:"embedding_id,omitempty"`
	// Error message if success is false.
	// Empty if success is true.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEmbeddingResponse) Reset() {
	*x = StoreEmbeddingResponse{}
	mi := &file_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEmbeddingResponse) ProtoMessage() {}

func (x *StoreEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*StoreEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *StoreEmbeddingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreEmbeddingResponse) GetEmbeddingId() int64 {
	if x != nil {
		return x.EmbeddingId
	}
	return 0
}

func (x *StoreEmbeddingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetEmbeddingsRequest specifies which article's embeddings to retrieve.
type GetEmbeddingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: ID of the article.
	// Must be a positive integer.
	ArticleId     int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingsRequest) Reset() {
	*x = GetEmbeddingsRequest{}
	mi := &file_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingsRequest) ProtoMessage() {}

func (x *GetEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*GetEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmbeddingsRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

// GetEmbeddingsResponse contains the retrieved embeddings.
type GetEmbeddingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of embeddings for the article.
	// Empty if no embeddings exist.
	Embeddings    []*ArticleEmbedding `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbeddingsResponse) Reset() {
	*x = GetEmbeddingsResponse{}
	mi := &file_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbeddingsResponse) ProtoMessage() {}

func (x *GetEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*GetEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmbeddingsResponse) GetEmbeddings() []*ArticleEmbedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

// SearchSimilarRequest contains the query for similarity search.
type SearchSimilarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Query embedding vector.
	// Must not be empty.
	Embedding []float32 `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Required: Type of embeddings to search against.
	// Valid values: "title", "content", "summary"
	EmbeddingType string `protobuf:"bytes,2,opt,name=embedding_type,json=embeddingType,proto3" json:"embedding_type,omitempty"`
	// Optional: Maximum number of results.
	// Default: 10, Maximum: 100
	// Values <= 0 will use default, values > 100 will be capped at 100.
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_embedding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSimilarRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SearchSimilarRequest) GetEmbeddingType() string {
	if x != nil {
		return x.EmbeddingType
	}
	return ""
}

func (x *SearchSimilarRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchSimilarResponse contains the search results.
type SearchSimilarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of similar articles, sorted by similarity (highest first).
	// May be empty if no similar articles are found.
	Articles      []*SimilarArticle `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_embedding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSimilarResponse) GetArticles() []*SimilarArticle {
	if x != nil {
		return x.Articles
	}
	return nil
}

// ArticleEmbedding represents a stored embedding with metadata.
type ArticleEmbedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this embedding.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the article this embedding belongs to.
	ArticleId int64 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Type of content that was embedded.
	EmbeddingType string `protobuf:"bytes,3,opt,name=embedding_type,json=embeddingType,proto3" json:"embedding_type,omitempty"`
	// AI provider that generated the embedding.
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// Model name that generated the embedding.
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// Dimension of the embedding vector.
	Dimension int32 `protobuf:"varint,6,opt,name=dimension,proto3" json:"dimension,omitempty"`
	// The embedding vector data.
	Embedding []float32 `protobuf:"fixed32,7,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Timestamp when the embedding was created (RFC 3339 format).
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the embedding was last updated (RFC 3339 format).
	UpdatedAt     string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleEmbedding) Reset() {
	*x = ArticleEmbedding{}
	mi := &file_embedding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleEmbedding) ProtoMessage() {}

func (x *ArticleEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleEmbedding.ProtoReflect.Descriptor instead.
func (*ArticleEmbedding) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{6}
}

func (x *ArticleEmbedding) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleEmbedding) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ArticleEmbedding) GetEmbeddingType() string {
	if x != nil {
		return x.EmbeddingType
	}
	return ""
}

func (x *ArticleEmbedding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ArticleEmbedding) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ArticleEmbedding) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *ArticleEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *ArticleEmbedding) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ArticleEmbedding) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// SimilarArticle represents an article with its similarity score.
type SimilarArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the similar article.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Cosine similarity score (0.0 to 1.0).
	// Higher values indicate more similar articles.
	// Note: Due to pgvector implementation, this is calculated as 1 - cosine_distance.
	Similarity    float32 `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarArticle) Reset() {
	*x = SimilarArticle{}
	mi := &file_embedding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarArticle) ProtoMessage() {}

func (x *SimilarArticle) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarArticle.ProtoReflect.Descriptor instead.
func (*SimilarArticle) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{7}
}

func (x *SimilarArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *SimilarArticle) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// DeleteEmbeddingRequest specifies which article's embeddings to delete.
type DeleteEmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: ID of the article whose embeddings should be deleted.
	// Must be a positive integer.
	ArticleId     int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmbeddingRequest) Reset() {
	*x = DeleteEmbeddingRequest{}
	mi := &file_embedding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmbeddingRequest) ProtoMessage() {}

func (x *DeleteEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEmbeddingRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

// DeleteEmbeddingResponse contains the result of the delete operation.
type DeleteEmbeddingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the operation succeeded (even if no embeddings existed).
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of embeddings that were deleted.
	DeletedCount int64 `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	// Error message if success is false.
	// Empty if success is true.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmbeddingResponse) Reset() {
	*x = DeleteEmbeddingResponse{}
	mi := &file_embedding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmbeddingResponse) ProtoMessage() {}

func (x *DeleteEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEmbeddingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteEmbeddingResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteEmbeddingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_embedding_proto protoreflect.FileDescriptor

const file_embedding_proto_rawDesc = "" +
	"\n" +
	"\x0fembedding.proto\x12\tembedding\"\xcb\x01\n" +
	"\x15StoreEmbeddingRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12%\n" +
	"\x0eembedding_type\x18\x02 \x01(\tR\rembeddingType\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1c\n" +
	"\tdimension\x18\x05 \x01(\x05R\tdimension\x12\x1c\n" +
	"\tembedding\x18\x06 \x03(\x02R\tembedding\"z\n" +
	"\x16StoreEmbeddingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fembedding_id\x18\x02 \x01(\x03R\vembeddingId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"5\n" +
	"\x14GetEmbeddingsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\"T\n" +
	"\x15GetEmbeddingsResponse\x12;\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1b.embedding.ArticleEmbeddingR\n" +
	"embeddings\"q\n" +
	"\x14SearchSimilarRequest\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12%\n" +
	"\x0eembedding_type\x18\x02 \x01(\tR\rembeddingType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"N\n" +
	"\x15SearchSimilarResponse\x125\n" +
	"\barticles\x18\x01 \x03(\v2\x19.embedding.SimilarArticleR\barticles\"\x94\x02\n" +
	"\x10ArticleEmbedding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\x12%\n" +
	"\x0eembedding_type\x18\x03 \x01(\tR\rembeddingType\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1c\n" +
	"\tdimension\x18\x06 \x01(\x05R\tdimension\x12\x1c\n" +
	"\tembedding\x18\a \x03(\x02R\tembedding\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"O\n" +
	"\x0eSimilarArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\"7\n" +
	"\x16DeleteEmbeddingRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\"}\n" +
	"\x17DeleteEmbeddingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x03R\fdeletedCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xeb\x02\n" +
	"\x10EmbeddingService\x12U\n" +
	"\x0eStoreEmbedding\x12 .embedding.StoreEmbeddingRequest\x1a!.embedding.StoreEmbeddingResponse\x12R\n" +
	"\rGetEmbeddings\x12\x1f.embedding.GetEmbeddingsRequest\x1a .embedding.GetEmbeddingsResponse\x12R\n" +
	"\rSearchSimilar\x12\x1f.embedding.SearchSimilarRequest\x1a .embedding.SearchSimilarResponse\x12X\n" +
	"\x0fDeleteEmbedding\x12!.embedding.DeleteEmbeddingRequest\x1a\".embedding.DeleteEmbeddingResponseB3Z1catchup-feed/internal/interface/grpc/pb/embeddingb\x06proto3"

var (
	file_embedding_proto_rawDescOnce sync.Once
	file_embedding_proto_rawDescData []byte
)

func file_embedding_proto_rawDescGZIP() []byte {
	file_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)))
	})
	return file_embedding_proto_rawDescData
}

var file_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_embedding_proto_goTypes = []any{
	(*StoreEmbeddingRequest)(nil),   // 0: embedding.StoreEmbeddingRequest
	(*StoreEmbeddingResponse)(nil),  // 1: embedding.StoreEmbeddingResponse
	(*GetEmbeddingsRequest)(nil),    // 2: embedding.GetEmbeddingsRequest
	(*GetEmbeddingsResponse)(nil),   // 3: embedding.GetEmbeddingsResponse
	(*SearchSimilarRequest)(nil),    // 4: embedding.SearchSimilarRequest
	(*SearchSimilarResponse)(nil),   // 5: embedding.SearchSimilarResponse
	(*ArticleEmbedding)(nil),        // 6: embedding.ArticleEmbedding
	(*SimilarArticle)(nil),          // 7: embedding.SimilarArticle
	(*DeleteEmbeddingRequest)(nil),  // 8: embedding.DeleteEmbeddingRequest
	(*DeleteEmbeddingResponse)(nil), // 9: embedding.DeleteEmbeddingResponse
}
var file_embedding_proto_depIdxs = []int32{
	6, // 0: embedding.GetEmbeddingsResponse.embeddings:type_name -> embedding.ArticleEmbedding
	7, // 1: embedding.SearchSimilarResponse.articles:type_name -> embedding.SimilarArticle
	0, // 2: embedding.EmbeddingService.StoreEmbedding:input_type -> embedding.StoreEmbeddingRequest
	2, // 3: embedding.EmbeddingService.GetEmbeddings:input_type -> embedding.GetEmbeddingsRequest
	4, // 4: embedding.EmbeddingService.SearchSimilar:input_type -> embedding.SearchSimilarRequest
	8, // 5: embedding.EmbeddingService.DeleteEmbedding:input_type -> embedding.DeleteEmbeddingRequest
	1, // 6: embedding.EmbeddingService.StoreEmbedding:output_type -> embedding.StoreEmbeddingResponse
	3, // 7: embedding.EmbeddingService.GetEmbeddings:output_type -> embedding.GetEmbeddingsResponse
	5, // 8: embedding.EmbeddingService.SearchSimilar:output_type -> embedding.SearchSimilarResponse
	9, // 9: embedding.EmbeddingService.DeleteEmbedding:output_type -> embedding.DeleteEmbeddingResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_embedding_proto_init() }
func file_embedding_proto_init() {
	if File_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_proto_msgTypes,
	}.Build()
	File_embedding_proto = out.File
	file_embedding_proto_goTypes = nil
	file_embedding_proto_depIdxs = nil
}
