// Copyright 2026 catchup-feed. All rights reserved.
// Embedding service protocol buffer definitions for gRPC communication.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: embedding.proto

package embedding

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmbeddingService_StoreEmbedding_FullMethodName = "/embedding.EmbeddingService/StoreEmbedding"
	EmbeddingService_GetEmbeddings_FullMethodName  = "/embedding.EmbeddingService/GetEmbeddings"
	EmbeddingService_SearchSimilar_FullMethodName  = "/embedding.EmbeddingService/SearchSimilar"
)

// EmbeddingServiceClient is the client API for EmbeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmbeddingService provides operations for managing article embeddings.
// This service is used by catchup-ai (Python) to store embeddings and perform
// similarity searches on articles.
type EmbeddingServiceClient interface {
	// StoreEmbedding stores or updates an embedding for an article.
	// If an embedding with the same (article_id, embedding_type, provider, model)
	// combination exists, it will be updated. Otherwise, a new embedding is created.
	StoreEmbedding(ctx context.Context, in *StoreEmbeddingRequest, opts ...grpc.CallOption) (*StoreEmbeddingResponse, error)
	// GetEmbeddings retrieves all embeddings for an article.
	// Returns an empty list if no embeddings exist for the article.
	GetEmbeddings(ctx context.Context, in *GetEmbeddingsRequest, opts ...grpc.CallOption) (*GetEmbeddingsResponse, error)
	// SearchSimilar finds articles similar to a query vector using cosine similarity.
	// Results are sorted by similarity score in descending order.
	SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error)
}

type embeddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingServiceClient(cc grpc.ClientConnInterface) EmbeddingServiceClient {
	return &embeddingServiceClient{cc}
}

func (c *embeddingServiceClient) StoreEmbedding(ctx context.Context, in *StoreEmbeddingRequest, opts ...grpc.CallOption) (*StoreEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreEmbeddingResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_StoreEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingServiceClient) GetEmbeddings(ctx context.Context, in *GetEmbeddingsRequest, opts ...grpc.CallOption) (*GetEmbeddingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmbeddingsResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_GetEmbeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingServiceClient) SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSimilarResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_SearchSimilar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingServiceServer is the server API for EmbeddingService service.
// All implementations must embed UnimplementedEmbeddingServiceServer
// for forward compatibility.
//
// EmbeddingService provides operations for managing article embeddings.
// This service is used by catchup-ai (Python) to store embeddings and perform
// similarity searches on articles.
type EmbeddingServiceServer interface {
	// StoreEmbedding stores or updates an embedding for an article.
	// If an embedding with the same (article_id, embedding_type, provider, model)
	// combination exists, it will be updated. Otherwise, a new embedding is created.
	StoreEmbedding(context.Context, *StoreEmbeddingRequest) (*StoreEmbeddingResponse, error)
	// GetEmbeddings retrieves all embeddings for an article.
	// Returns an empty list if no embeddings exist for the article.
	GetEmbeddings(context.Context, *GetEmbeddingsRequest) (*GetEmbeddingsResponse, error)
	// SearchSimilar finds articles similar to a query vector using cosine similarity.
	// Results are sorted by similarity score in descending order.
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
	mustEmbedUnimplementedEmbeddingServiceServer()
}

// UnimplementedEmbeddingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbeddingServiceServer struct{}

func (UnimplementedEmbeddingServiceServer) StoreEmbedding(context.Context, *StoreEmbeddingRequest) (*StoreEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreEmbedding not implemented")
}
func (UnimplementedEmbeddingServiceServer) GetEmbeddings(context.Context, *GetEmbeddingsRequest) (*GetEmbeddingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbeddings not implemented")
}
func (UnimplementedEmbeddingServiceServer) SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSimilar not implemented")
}
func (UnimplementedEmbeddingServiceServer) mustEmbedUnimplementedEmbeddingServiceServer() {}
func (UnimplementedEmbeddingServiceServer) testEmbeddedByValue()                          {}

// UnsafeEmbeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingServiceServer will
// result in compilation errors.
type UnsafeEmbeddingServiceServer interface {
	mustEmbedUnimplementedEmbeddingServiceServer()
}

func RegisterEmbeddingServiceServer(s grpc.ServiceRegistrar, srv EmbeddingServiceServer) {
	// If the following call panics, it indicates UnimplementedEmbeddingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbeddingService_ServiceDesc, srv)
}

func _EmbeddingService_StoreEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).StoreEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_StoreEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).StoreEmbedding(ctx, req.(*StoreEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingService_GetEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).GetEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_GetEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).GetEmbeddings(ctx, req.(*GetEmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingService_SearchSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).SearchSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_SearchSimilar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).SearchSimilar(ctx, req.(*SearchSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingService_ServiceDesc is the grpc.ServiceDesc for EmbeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embedding.EmbeddingService",
	HandlerType: (*EmbeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreEmbedding",
			Handler:    _EmbeddingService_StoreEmbedding_Handler,
		},
		{
			MethodName: "GetEmbeddings",
			Handler:    _EmbeddingService_GetEmbeddings_Handler,
		},
		{
			MethodName: "SearchSimilar",
			Handler:    _EmbeddingService_SearchSimilar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "embedding.proto",
}
